// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2KSwvM6UhYkfYtwpGepEgTuSOQQ2hwj0',
    appId: '1:492342451483:web:132feb7a1b1d224f8b87be',
    messagingSenderId: '492342451483',
    projectId: 'movie-list-bbb63',
    authDomain: 'movie-list-bbb63.firebaseapp.com',
    storageBucket: 'movie-list-bbb63.appspot.com',
    measurementId: 'G-SG7HG30CHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC3Pc4sqIR5zTcjds_oHlXBVH5m53lxm0',
    appId: '1:492342451483:android:e1a542b1b93a379d8b87be',
    messagingSenderId: '492342451483',
    projectId: 'movie-list-bbb63',
    storageBucket: 'movie-list-bbb63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWwB7YwF5wrIUlC0SrxaR73ZDiBB_gMNQ',
    appId: '1:492342451483:ios:f4866fd3f7c4ab1e8b87be',
    messagingSenderId: '492342451483',
    projectId: 'movie-list-bbb63',
    storageBucket: 'movie-list-bbb63.appspot.com',
    iosClientId: '492342451483-3caaee5dfnqm9sf0t5d1dlb4b9hd400l.apps.googleusercontent.com',
    iosBundleId: 'com.draco.movieList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWwB7YwF5wrIUlC0SrxaR73ZDiBB_gMNQ',
    appId: '1:492342451483:ios:f4866fd3f7c4ab1e8b87be',
    messagingSenderId: '492342451483',
    projectId: 'movie-list-bbb63',
    storageBucket: 'movie-list-bbb63.appspot.com',
    iosClientId: '492342451483-3caaee5dfnqm9sf0t5d1dlb4b9hd400l.apps.googleusercontent.com',
    iosBundleId: 'com.draco.movieList',
  );
}
